import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/header";
import { Toaster } from "react-hot-toast";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "House Rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://res.cloudinary.com/ddlpde95c/image/upload/v1725023546/service-1_rexnbz.png"
        />
      </head>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <Toaster position="top-right" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
